name: Pull and Merge Books

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  pull_books:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"

      - name: Download book sources
        run: |
          curl -O http://www.yckceo.com/yuedu/shuyuans/json/id/180.json
          curl -O http://www.yckceo.com/yuedu/shuyuans/json/id/185.json
          # Add more curl commands for other book sources

      - name: Archive book sources
        uses: actions/upload-artifact@v2
        with:
          name: book-sources
          path: |
            180.json
            185.json
            # Add more file paths for other book sources

  merge_books:
    needs: pull_books
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download book sources
        uses: actions/download-artifact@v2
        with:
          name: book-sources

      - name: Merge books
        run: |
          cat 180.json 185.json > merged_books.json
          # Add more cat commands for merging other book sources

      - name: Show working tree status
        run: git status

      - name: Add merged_books.json
        run: git add .

      - name: Push changes
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: git push origin main
