name: Pull Books

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install --no-package-lock

      - name: Pull books
        run: |
          # Replace the URLs with the actual book source URLs you want to pull
          curl -O https://fastly.jsdelivr.net/gh/mumuceo/file01/202311/1935_9862a49a0063d95f9abc729c15992948.json
          curl -O https://cdn.jsdelivr.net/gh/mumuceo/file01/202310/2948_6d4e3f2cb45e82ab05970a5173e6bd5b.json
          
          # Add more curl commands for additional book sources

      - name: Merge books
        run: |
          # Delete the existing merged_books.json file
          rm -f merged_books.json

          # Initialize merged_books.json as an empty array
          echo '[]' > merged_books.json

          # Merge the pulled book JSON files into merged_books.json
          for file in *.json; do
            jq --slurpfile input "$file" '. + $input[0]' merged_books.json > merged.tmp && mv merged.tmp merged_books.json
          done

      - name: Configure Git
        run: |
         git config --local user.email "${{ secrets.USER_EMAIL }}"
         git config --local user.name "${{ secrets.USER_NAME }}"
         git config --local credential.helper store --file=.git-credentials
         echo "https://github.com/${{ github.repository }}:${{ secrets.REPO_TOKEN }}" > .git-credentials

      - name: Add files to Git
        run: |
          git add .git-credentials
          git add merged_books.json

      - name: Commit and push changes
        run: |
          git commit -m "Merge books"
          git -c credential.helper="store --file=.git-credentials" push
