name: Pull and Merge Book Sources

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull and Merge Book Sources
        run: |
          # 创建一个空的合并结果文件
          echo "[" > merged_sources.json

          # 遍历书源 URL 列表
          for url in "http://www.yckceo.com/yuedu/shuyuans/json/id/180.json" "http://www.example.com/book_source2.json" "http://www.example.com/book_source3.json"
          do
            # 拉取书源内容并追加到合并结果文件
            curl -s $url >> merged_sources.json
            echo "," >> merged_sources.json
          done

          # 移除最后一个逗号
          sed -i '$ s/,$//' merged_sources.json

          # 添加合并结果的结尾
          echo "]" >> merged_sources.json

      - name: Configure Git
        run: |
         git config --local user.email "${{ secrets.USER_EMAIL }}"
         git config --local user.name "${{ secrets.USER_NAME }}"
         git config --local credential.helper store --file=.git-credentials
         echo "https://github.com/${{ github.repository }}:${{ secrets.REPO_TOKEN }}" > .git-credentials

      - name: Commit and push changes
        run: |
          git add merged_books.json
          git commit -m "Merge books"
          git -c credential.helper="store --file=.git-credentials" push
