name: Pull and Merge Books

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  pull_books:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull books
        run: |
          curl -o book1.json http://www.yckceo.com/yuedu/shuyuans/json/id/180.json
          curl -o book2.json http://www.yckceo.com/yuedu/shuyuans/json/id/185.json
          # Add more curl commands for additional book sources if needed

      - name: Merge books
        run: |
          cat book*.json > merged_books.json

  commit_changes:
    needs: pull_books
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
         git config --local user.email "${{ secrets.USER_EMAIL }}"
         git config --local user.name "${{ secrets.USER_NAME }}"

      - name: Add changes to Git
        run: |
          git add merged_books.json

      - name: Commit changes
        run: |
          git commit -m "Merge books"

      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          branch: main
