name: Delete Workflow Runs

on:
  workflow_dispatch:

jobs:
  delete_runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: shidahuilang/shuyuan
          keep_minimum_runs: 0
          baseUrl: https://api.github.com
