name: 清理Actions
on:
  workflow_dispatch:

  schedule:
    - cron: 0 3 */3 * *

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete GitHub Actions workflow runs
        uses: JuvenileQ/delete-workflow-runs@v1.0.0
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 0
          retain_man: ${{ env.retain_min }}
