name: ipa
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      USER_EMAIL: "you@example.com"
      USER_NAME: "Your Name"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
         python-version: "3.10"

      - name: 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 运行脚本
        run: python ipa.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Set up Git identity
        run: |
          git config --local user.email "${{ env.USER_EMAIL }}"
          git config --local user.name "${{ env.USER_NAME }}"

      - name: 检查是否有文件变更
        run: |
          git diff --quiet || git add . && git commit -m "ipa应用合并" && git push

      - name: Telegram通知
        run: |
          curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=ipa应用合并更新合并完成!分支：${{ github.ref }}"
