on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 */3 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"  # 替换为你想要使用的 Python 版本

      - name: Create books directory
        run: |
          if [ ! -d "4.0" ]; then
            mkdir 4.0
          fi

      - name: Install dependencies
        run: pip install -r requirements.txt  # 替换为你的依赖项安装命令

      - name: Pull 4.0
        run: |
          cd 4.0

          # 下载 JSON 文件
          curl -O https://testingcf.jsdelivr.net/gh/mumuceo/file01/202311/3289_2d1ceb82e5cf2efcf81ca4d086d9b76e.json
          curl -O https://cdn.jsdelivr.net/gh/mumuceo/file01/202311/3351_9c22facf74af60698a8b25b0edcadeec.json
          curl -O https://fastly.jsdelivr.net/gh/mumuceo/file01/202311/3264_0740c7c5849bc070697ced91537ff4ee.json

      - name: Merge books
        run: |
          cd 3.0

          # 删除已存在的 merged_books.json 文件
          rm -f merged_books.json

          # 初始化 merged_books.json 为空数组
          echo '[]' > merged_books.json

          # 将下载的书籍 JSON 文件合并到 merged_books.json
          python merge_books.py  # 替换为你的合并脚本命令

      - name: Configure Git
        run: |
         git config --local user.email "${{ secrets.USER_EMAIL }}"
         git config --local user.name "${{ secrets.USER_NAME }}"
         git config --local credential.helper store --file=.git-credentials
         echo "https://github.com/${{ github.repository }}:${{ secrets.REPO_TOKEN }}" > .git-credentials

      - name: Add files to Git
        run: |
          git add .git-credentials
          git add 4.0/merged_books.json
          git add 4.0/*.json

      - name: Commit and push changes
        run: |
          git commit -m "Merge books"
          git -c credential.helper="store --file=.git-credentials" push

      - name: Send Telegram notification
        run: |
         curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
         -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
         -d "text=3.0阅读书源更新完成!分支：${{ github.ref }}"
