name: test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
    - name: Create books directory
      run: |
          if [ ! -d "4.0" ]; then
            mkdir 4.0
          fi

    - name: Install dependencies
      run: npm install --no-package-lock

    - name: Pull 4.0
      run: |
          cd 4.0


          curl -O https://testingcf.jsdelivr.net/gh/mumuceo/file01/202311/3289_2d1ceb82e5cf2efcf81ca4d086d9b76e.json
          curl -O https://cdn.jsdelivr.net/gh/mumuceo/file01/202311/3351_9c22facf74af60698a8b25b0edcadeec.json
          curl -O https://fastly.jsdelivr.net/gh/mumuceo/file01/202311/3264_0740c7c5849bc070697ced91537ff4ee.json

          
          


    - name: Merge books
      run: |
          cd 3.0

          # Delete the existing merged_books.json file
          rm -f merged_books.json

          # Initialize merged_books.json as an empty array
          echo '[]' > merged_books.json

          # Merge the pulled book JSON files into merged_books.json
          for file in *.json; do
            jq --slurpfile input "$file" '. + $input[0]' merged_books.json > merged.tmp && mv merged.tmp merged_books.json
          done

    - name: Configure Git
      run: |
         git config --local user.email "${{ secrets.USER_EMAIL }}"
         git config --local user.name "${{ secrets.USER_NAME }}"
         git config --local credential.helper store --file=.git-credentials
         echo "https://github.com/${{ github.repository }}:${{ secrets.REPO_TOKEN }}" > .git-credentials

    - name: Add files to Git
      run: |
          git add .git-credentials
          git add 4.0/merged_books.json
          git add 4.0/*.json


    - name: Commit and push changes
      run: |
          git commit -m "Merge books"
          git -c credential.helper="store --file=.git-credentials" push
          
    - name: Send Telegram notification
      run: |
         curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
         -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
         -d "text=3.0阅读书源更新完成!分支：${{ github.ref }}"   
